
modLoader = "javafml" #mandatory
loaderVersion="[1,)"
license="${license}"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]]
modId="${modId}"
version="${modVersion}"
displayName="${displayName}"
logoFile= "${modId}_title.png"
credits="Epic Fight, Forixaim for initial Neoforge port"
authors="${authors}"


description="${description}"


[[mixins]]
config="mixins.${modId}.json"


[[dependencies."${modId}"]]
modId="epicfight"
mandatory=true
versionRange="[21.17,)"
ordering="AFTER"
side="BOTH"

[[dependencies."${modId}"]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforgeVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${modId}"]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft}]"
ordering = "NONE"
side = "BOTH"
